# Install MiniPC Software 
---
- name: Install Debian Image Dependencies
  hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml

  tasks:
    - name: Update And upgrade Apt Packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Dependencies
      apt:
        name:
          - htop
          - git
          - curl
          - zsh
          - vim
          - net-tools
        state: present


    - name: Install Python, Dev And Pip
      apt:
        name:
          - python3
          - python3-dev
          - python3-pip
          - python3-serial
        state: present


    - name: Create a Symbolic Link Python3
      ansible.builtin.file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
        force: yes

    - name: Create a Symbolic Link Pip3
      ansible.builtin.file:
        src: /usr/bin/pip3
        dest: /usr/bin/pip
        state: link
        force: yes



    - name: Copy vimrc template to .vimrc for users
      template:
        src: vimrc.j2
        dest: /home/sigmadev/.vimrc
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: 0644

    - name: Copy vimrc template to .vimrc for root
      template:
        src: vimrc.j2
        dest: /root/.vimrc
        owner: root
        group: root
        mode: 0644

    - name: Downloading Sigma Software
      git:
        repo: https://{{gitlabuser | urlencode}}:{{gitlabpassword | urlencode}}@gitlab.com/sigma-telecom/sigma-rds.git
        dest: /tmp/sigma-rds
        version: development
        accept_hostkey: true
        update: yes