# Install MiniPC Software 
---
- name: Install Debian Image Dependencies
  hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml

  tasks:
    - name: Update And upgrade Apt Packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Dependencies
      apt:
        name:
          - htop
          - git
          - curl
          - zsh
          - vim
          - net-tools
        state: present

    - name: Copy vimrc template to .vimrc for users
      template:
        src: vimrc.j2
        dest: /home/{{ ansible_user }}/.vimrc
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: 0644

    - name: Copy vimrc template to .vimrc for root
      template:
        src: vimrc.j2
        dest: /root/.vimrc
        owner: root
        group: root
        mode: 0644

    - name: Downloading Sigma Software
      git:
        repo: https://{{gitlabuser | urlencode}}:{{gitlabpassword | urlencode}}@gitlab.com/sigma-telecom/sigma-rds.git
        dest: /tmp/sigma-rds
        version: development
        accept_hostkey: true
        update: yes