# Install MiniPC Software 
---
- name: Install Debian Image Dependencies   
  hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml

  tasks:
  - name: Update And upgrade Apt Packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Dependencies
    apt:
        name:
            - htop
            - git
            - curl
            - zsh
            - vim
            - net-tools
        state: present

  - name: Downloading Sigma Software
    git:
      repo: https://{{gitlabuser | urlencode}}:{{gitlabpassword | urlencode}}@gitlab.com/sigma-telecom/sigma-rds.git
      dest: /tmp/sigma-rds
      version: development
      accept_hostkey: true

  # - name: Install RCC tool
  #   get_url:
  #     url: https://downloads.robocorp.com/rcc/releases/v14.6.0/linux64/rcc
  #     dest: /usr/local/bin/rcc
  #     mode: '0755'