# Install MiniPC Software
---
- name: Upload icinga basket
  hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml

  tasks:

  - name: Restart icinga-director service
    service:
      name: icinga-director
      state: restarted

  - name: Copy basket.json to the remote host from
    copy:
      src: "{{ local_basket_file }}"
      dest: "{{ remote_basket_file }}"
      mode: '0644'
    become: true
    become_user: root

  - name: Execute command with input file
    shell: cat "{{ remote_basket_file }}" | icingacli director basket restore
    become: true
    become_user: root


  - name: Deploying The Changes
    command: icingacli director config deploy
