# Install MiniPC Software
---
- name: Restarting extra modules services
  hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml

  tasks:
  - name: Restart icinga-director service
    service:
      name: icinga-director
      state: restarted
