# Install MiniPC Software
---
- name: IcingaWeb 2 Setup
  hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml

  tasks:



# IcingaWeb2
  - name: Create apache root page
    shell:
      cmd: echo {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} > /var/www/html/index.html
  - name: Enable rewrite apache module
    shell:
      cmd: a2enmod rewrite

  - name: Modify /etc/icingaweb2/ permissions
    file:
      path: /etc/icingaweb2/
      owner: "www-data"
      group: "icingaweb2"
      recurse: yes

  - name: Modify /usr/share/icingaweb2/ permissions
    file:
      path: /usr/share/icingaweb2/
      owner: "www-data"
      group: "icingaweb2"
      recurse: yes

  - name: Modify apache default site config
    template:
      src: apache-site.j2
      dest: /etc/apache2/sites-enabled/000-default.conf

  - name: Restart Apache service
    service:
      name: apache2
      state: restarted

  - name: enable icingaweb2 setup module
    shell:
      cmd: icingacli module enable setup

  - name: Create and get setup token
    shell:
      cmd: icingacli setup token create && cat /etc/icingaweb2/setup.token

  - name: Fetch a "setup.token" file
    fetch:
      src: /etc/icingaweb2/setup.token
      dest: /tmp/setup.token
