# Install MiniPC Software 
---
- name: Install Debian Image Dependencies
  hosts: icinga_master
  become: true
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: sigmadev
        - username: root
  vars_files:
    - ../vars.yaml

  tasks:
    - name: Install zsh-autosuggestions plugin
      ansible.builtin.shell: git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install zsh-syntax-highlighting plugin
      ansible.builtin.shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Add zsh plugins to .zshrc file
      lineinfile:
        path: ~/.zshrc
        line: 'plugins=(zsh-autosuggestions zsh-syntax-highlighting)'