- hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml
  tasks:

    - name: Installing Plugins
      copy:
        remote_src: true
        src: /tmp/sigma-rds/src/plugins/check_status.py
        dest: /usr/lib/nagios/plugins/

    - name: Add +x permission to check_status.py
      file:
        path: /usr/lib/nagios/plugins/check_status.py
        mode: +x