- hosts: icinga_master
  become: true
  vars_files:
    - ../vars.yaml
  tasks:

    - name: Installing Status Plugin
      copy:
        remote_src: true
        src: /tmp/sigma-rds/src/plugins/check_status.py
        dest: /usr/lib/nagios/plugins/

    - name: Add +x permission to check_status.py
      file:
        path: /usr/lib/nagios/plugins/check_status.py
        mode: +x

    - name: Installing Status Plugin
      copy:
        remote_src: true
        src: /tmp/sigma-rds/src/plugins/check_eth.py
        dest: /usr/lib/nagios/plugins/

    - name: Add +x permission to check_eth.py
      file:
        path: /usr/lib/nagios/plugins/check_eth.py
        mode: +x

    - name: Installing Status Plugin
      copy:
        remote_src: true
        src: /tmp/sigma-rds/src/plugins/drs.py
        dest: /usr/lib/nagios/plugins/

    - name: Add +x permission to drs.py
      file:
        path: /usr/lib/nagios/plugins/drs.py
        mode: +x


    - name: Installing Memory Plugin
      copy:
        remote_src: true
        src: /tmp/sigma-rds/src/plugins/check_memory.py
        dest: /usr/lib/nagios/plugins/

    - name: Add +x permission to check_memory.py
      file:
        path: /usr/lib/nagios/plugins/check_memory.py
        mode: +x

    - name: Installing Disk Plugin
      copy:
        remote_src: true
        src: /tmp/sigma-rds/src/plugins/check_disk.py
        dest: /usr/lib/nagios/plugins/

    - name: Add +x permission to check_disk.py
      file:
        path: /usr/lib/nagios/plugins/check_disk.py
        mode: +x

    - name: Installing Load Plugin
      copy:
        remote_src: true
        src: /tmp/sigma-rds/src/plugins/check_load.py
        dest: /usr/lib/nagios/plugins/

    - name: Add +x permission to check_disk.py
      file:
        path: /usr/lib/nagios/plugins/check_load.py
        mode: +x