---
- name: Fix hosts with no python at all
  hosts: all
  gather_facts: false

  tasks:
    - name: Perform a dirty OS detection if python is not installed
      raw: |-
        if which python > /dev/null || which python3 > /dev/null; then
          echo installed
        else
          sed -n "s/^NAME=\"\(.*\)\"/\\1/p" /etc/os-release
        fi
      changed_when: false
      register: dirty_detect

    - name: Print message when already installed
      debug:
        msg: Host {{ inventory_hostname }} already has python
      when: dirty_detect.stdout_lines[0] == 'installed'

    - name: Install python on Alpine if needed
      raw: |-
        apk add python3
      become: true
      when: dirty_detect.stdout_lines[0] == 'Alpine Linux'
