<div class="controls">
  <?= /** @var \Icinga\Web\Widget\Tabs $tabs */ $tabs ?>
</div>
<div class="content">
    <center><h1>SET DRU</h1></center>
    
    <strong>Id</strong>: <?= $this->id ?>
    <br>
    <strong>Descripcion</strong>: <?= $this->descripcion ?>
    <br> 
    <strong>Trama</strong>: <?= $this->trama ?>
    <hr>   
    <?= /** @var \Icinga\Module\Rs485\Forms\SetdruForm $form */ $form ?>
</div>


