# Install MiniPC Software 
---
- name: Install Debian Image dependencies   
  hosts: icinga_satellite
  become: true
  roles:
  - role: gantsign.oh-my-zsh
    users:
      - username: sigmadev
      - username: root

  tasks:
    
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Dependencies
    apt:
        name:
            - htop
            - git
            - curl
            - zsh
            - vim
        state: present
    register: output


  # - name: Download oh-my-zsh now
  #   get_url:
  #     url:  https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  #     dest: /tmp
  #     mode: '0777'

  # - name: Install oh-my-zsh now
  #   shell: ./install.sh
  #   args:
  #       chdir: /tmp


   