# Install MiniPC Software 
---
- name: Install Debian Image Dependencies   
  hosts: icinga_satellite
  become: true
  roles:
  - role: gantsign.oh-my-zsh
    users:
      - username: sigmadev
      - username: root

  tasks:
    
  - name: Update And upgrade Apt Packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Dependencies
    apt:
        name:
            - htop
            - git
            - curl
            - zsh
            - vim
        state: present
    register: output