---

- name: Create Service Apply Rules
  hosts: all
  become: true
  vars_files:
    - ./vars.yaml


- name: "Director Configuration"
  import_playbook: playbooks/director_config.yaml

- name: "Extra Customizations"
  import_playbooks: playbooks/extras_customizations.yaml