---

- name: Create Service Apply Rules
  hosts: all
  become: true
  vars_files:
    - ./vars.yaml


- name: "Basket Configuration"
  import_playbook: playbooks/basket_config.yaml

- name: "Extra Customizations"
  import_playbook: playbooks/extras_customizations.yaml+