---

- name: Install DRS Master Software
  hosts: all
  become: true
  vars_files:
    - ./vars.yaml


- name: "Installing Extra Modules"
  import_playbook: playbooks/extras.yaml

- name: "Plugin Installation"
  import_playbook: playbooks/rs485_plugin.yaml


