---

- name: Install DRS Satellite Software
  hosts: all
  become: true
  vars_files:
    - ./vars.yaml

- name: "Installing dependencies"
  import_playbook: playbooks/dependencies.yaml

- name: "Installing Icinga2 Software"
  import_playbook: playbooks/icinga2.yaml

- name: "Configure Icinga2 Software"
  import_playbook: playbooks/icinga2config.yaml
