---
- name: Install DRS Satellite Software
  hosts: all
  become: true
  vars_files:
    - ./vars.yaml
  roles:
    - ansible-icinga2

- name: "Installing Icinga2 Software"
  import_playbook: playbooks/icinga2.yaml
